<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-01-10T20:58:25 IST" name="Suite" finished-at="2024-01-10T20:58:32 IST" duration-ms="7897">
    <groups>
      <group name="Error Handling">
        <method signature="ErrorValidation.loginError()[pri:0, instance:FrameWork.tests.ErrorValidation@71ba6d4e]" name="loginError" class="FrameWork.tests.ErrorValidation"/>
      </group> <!-- Error Handling -->
    </groups>
    <test started-at="2024-01-10T20:58:25 IST" name="Submit Order validation" finished-at="2024-01-10T20:58:25 IST" duration-ms="67">
      <class name="FrameWork.tests.StandAloneTest">
        <test-method signature="alone(java.util.HashMap)[pri:0, instance:FrameWork.tests.StandAloneTest@bae7dc0]" started-at="2024-01-10T20:58:25 IST" name="alone" finished-at="2024-01-10T20:58:25 IST" duration-ms="0" status="FAIL">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Cannot inject @Test annotated Method [alone] with [class java.util.HashMap].
For more information on native dependency injection please refer to https://testng.org/doc/documentation-main.html#native-dependency-injection]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Cannot inject @Test annotated Method [alone] with [class java.util.HashMap].
For more information on native dependency injection please refer to https://testng.org/doc/documentation-main.html#native-dependency-injection
at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:439)
at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:353)
at org.testng.internal.Parameters.createParameters(Parameters.java:708)
at org.testng.internal.Parameters.handleParameters(Parameters.java:884)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- alone -->
        <test-method signature="orderValidation()[pri:0, instance:FrameWork.tests.StandAloneTest@bae7dc0]" started-at="2024-01-10T20:58:25 IST" name="orderValidation" finished-at="2024-01-10T20:58:25 IST" depends-on-methods="FrameWork.tests.StandAloneTest.alone" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method StandAloneTest.orderValidation()[pri:0, instance:FrameWork.tests.StandAloneTest@bae7dc0] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method StandAloneTest.orderValidation()[pri:0, instance:FrameWork.tests.StandAloneTest@bae7dc0] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderValidation -->
      </class> <!-- FrameWork.tests.StandAloneTest -->
    </test> <!-- Submit Order validation -->
    <test started-at="2024-01-10T20:58:25 IST" name="Error Validation on Login page" finished-at="2024-01-10T20:58:32 IST" duration-ms="7897">
      <class name="FrameWork.tests.ErrorValidation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:FrameWork.tests.ErrorValidation@71ba6d4e]" started-at="2024-01-10T20:58:25 IST" name="launchApplication" finished-at="2024-01-10T20:58:32 IST" duration-ms="7063" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginError()[pri:0, instance:FrameWork.tests.ErrorValidation@71ba6d4e]" started-at="2024-01-10T20:58:32 IST" name="loginError" finished-at="2024-01-10T20:58:32 IST" duration-ms="437" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginError -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:FrameWork.tests.ErrorValidation@71ba6d4e]" started-at="2024-01-10T20:58:32 IST" name="tearDown" finished-at="2024-01-10T20:58:32 IST" duration-ms="339" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- FrameWork.tests.ErrorValidation -->
    </test> <!-- Error Validation on Login page -->
  </suite> <!-- Suite -->
</testng-results>
